export const IPDE_INTENTS = [
  'GREETING',
  'REQUEST_INFORMATION',
  'REQUEST_SUBJECT_LIST',
  'PROVIDE_SUBJECTS',
  'PROVIDE_PRESELECTED_TOPICS',
  'PROVIDE_TOPIC_SELECTION',
  'PROVIDE_PRODUCT_TYPE',
  'PROVIDE_ISSUER_PREFERENCE',
  'PROVIDE_FULL_NAME',
  'REQUEST_PROMOTION',
  'REQUEST_PRICE',
  'REQUEST_DISCOUNT',
  'REQUEST_MODEL_PDF',
  'REQUEST_PAYMENT_METHODS',
  'CONFIRM',
  'CORRECT_OR_REJECT',
  'REQUEST_HUMAN',
  'PAYMENT_PROOF_MENTION',
  'OTHER',
] as const;

export const IPDE_REQUEST_PATHS = [
  'DIRECT_TOPICS',
  'CATALOG_LIST',
  'UNDETERMINED',
] as const;

export const IPDE_REQUESTED_ARTIFACTS = [
  'PROMOTION_IMAGE',
  'PAYMENT_METHODS_IMAGE',
  'MODEL_PDF',
] as const;

export const IPDE_ISSUER_CODES = ['CAC', 'UNT', 'UNSPECIFIED'] as const;

export const IPDE_ISSUER_VARIANT_CODES = [
  'CAC_DECANO',
  'UNT_DIRECTORAL',
  'UNT_POSGRADO',
  'UNSPECIFIED',
] as const;

export const IPDE_AMBIGUITY_CODES = [
  'AMBIGUOUS_SUBJECT',
  'AMBIGUOUS_ACRONYM',
  'AMBIGUOUS_TOPIC_SELECTION',
  'AMBIGUOUS_PRODUCT_TYPE',
  'AMBIGUOUS_ISSUER',
  'POSSIBLE_NAME_WITHOUT_CONTEXT',
  'INSUFFICIENT_INFORMATION',
] as const;

export const IPDE_CONFIRMATION_VALUES = [
  'CONFIRMS',
  'REJECTS_OR_CORRECTS',
  'UNCLEAR',
] as const;

export const IPDE_CONTEXT_MESSAGE_ROLES = ['USER', 'ASSISTANT'] as const;

export const DEFAULT_IPDE_UNDERSTANDING_MODEL = 'gpt-5.4-mini';
export const DEFAULT_IPDE_UNDERSTANDING_PROMPT_VERSION = 'v1';
